/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#include "Abort.h"

static asn_per_constraints_t asn_PER_type_reason_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_reason_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct reason, choice.p_abortCause),
		(ASN_TAG_CLASS_APPLICATION | (10 << 2)),
		0,
		&asn_DEF_P_AbortCause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"p-abortCause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct reason, choice.u_abortCause),
		(ASN_TAG_CLASS_APPLICATION | (11 << 2)),
		0,
		&asn_DEF_DialoguePortion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"u-abortCause"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_reason_tag2el_3[] = {
    { (ASN_TAG_CLASS_APPLICATION | (10 << 2)), 0, 0, 0 }, /* p-abortCause */
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 1, 0, 0 } /* u-abortCause */
};
static asn_CHOICE_specifics_t asn_SPC_reason_specs_3 = {
	sizeof(struct reason),
	offsetof(struct reason, _asn_ctx),
	offsetof(struct reason, present),
	sizeof(((struct reason *)0)->present),
	asn_MAP_reason_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reason_3 = {
	"reason",
	"reason",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_reason_constr_3, CHOICE_constraint },
	asn_MBR_reason_3,
	2,	/* Elements count */
	&asn_SPC_reason_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Abort_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Abort, dtid),
		(ASN_TAG_CLASS_APPLICATION | (9 << 2)),
		0,
		&asn_DEF_DestTransactionID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dtid"
		},
	{ ATF_POINTER, 1, offsetof(struct Abort, reason),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_reason_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reason"
		},
};
static const int asn_MAP_Abort_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_Abort_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Abort_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (9 << 2)), 0, 0, 0 }, /* dtid */
    { (ASN_TAG_CLASS_APPLICATION | (10 << 2)), 1, 0, 0 }, /* p-abortCause */
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 1, 0, 0 } /* u-abortCause */
};
asn_SEQUENCE_specifics_t asn_SPC_Abort_specs_1 = {
	sizeof(struct Abort),
	offsetof(struct Abort, _asn_ctx),
	asn_MAP_Abort_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Abort_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Abort = {
	"Abort",
	"Abort",
	&asn_OP_SEQUENCE,
	asn_DEF_Abort_tags_1,
	sizeof(asn_DEF_Abort_tags_1)
		/sizeof(asn_DEF_Abort_tags_1[0]), /* 1 */
	asn_DEF_Abort_tags_1,	/* Same as above */
	sizeof(asn_DEF_Abort_tags_1)
		/sizeof(asn_DEF_Abort_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Abort_1,
	2,	/* Elements count */
	&asn_SPC_Abort_specs_1	/* Additional specs */
};

