/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#include "DialoguePortion.h"

/*
 * This type is implemented using ANY,
 * so here we adjust the DEF accordingly.
 */
asn_TYPE_descriptor_t asn_DEF_DialoguePortion = {
	"DialoguePortion",
	"DialoguePortion",
	&asn_OP_ANY,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, ANY_constraint },
	0, 0,	/* No members */
	&asn_SPC_ANY_specs	/* Additional specs */
};

