/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_End_H_
#define	_End_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DestTransactionID.h"
#include "DialoguePortion.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ComponentPortion;

/* End */
typedef struct End {
	DestTransactionID_t	 dtid;
	DialoguePortion_t	*dialoguePortion	/* OPTIONAL */;
	struct ComponentPortion	*components	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} End_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_End;
extern asn_SEQUENCE_specifics_t asn_SPC_End_specs_1;
extern asn_TYPE_member_t asn_MBR_End_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ComponentPortion.h"

#endif	/* _End_H_ */
#include <asn_internal.h>
