/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_ERROR_H_
#define	_ERROR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ERROR_PR {
	ERROR_PR_NOTHING,	/* No components present */
	ERROR_PR_localValue,
	ERROR_PR_globalValue
} ERROR_PR;

/* ERROR */
typedef struct ERROR {
	ERROR_PR present;
	union ERROR_u {
		long	 localValue;
		OBJECT_IDENTIFIER_t	 globalValue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ERROR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ERROR;
extern asn_CHOICE_specifics_t asn_SPC_ERROR_specs_1;
extern asn_TYPE_member_t asn_MBR_ERROR_1[2];
extern asn_per_constraints_t asn_PER_type_ERROR_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ERROR_H_ */
#include <asn_internal.h>
