/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#include "Invoke.h"

asn_TYPE_member_t asn_MBR_Invoke_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Invoke, invokeID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_InvokeIdType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"invokeID"
		},
	{ ATF_POINTER, 1, offsetof(struct Invoke, linkedID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InvokeIdType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"linkedID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Invoke, operationCode),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_OPERATION,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"operationCode"
		},
	{ ATF_ANY_TYPE | ATF_POINTER, 1, offsetof(struct Invoke, parameter),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"parameter"
		},
};
static const int asn_MAP_Invoke_oms_1[] = { 1, 3 };
static const ber_tlv_tag_t asn_DEF_Invoke_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Invoke_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* invokeID */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 0 }, /* localValue */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 2, 0, 0 }, /* globalValue */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* linkedID */
};
asn_SEQUENCE_specifics_t asn_SPC_Invoke_specs_1 = {
	sizeof(struct Invoke),
	offsetof(struct Invoke, _asn_ctx),
	asn_MAP_Invoke_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Invoke_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Invoke = {
	"Invoke",
	"Invoke",
	&asn_OP_SEQUENCE,
	asn_DEF_Invoke_tags_1,
	sizeof(asn_DEF_Invoke_tags_1)
		/sizeof(asn_DEF_Invoke_tags_1[0]), /* 1 */
	asn_DEF_Invoke_tags_1,	/* Same as above */
	sizeof(asn_DEF_Invoke_tags_1)
		/sizeof(asn_DEF_Invoke_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Invoke_1,
	4,	/* Elements count */
	&asn_SPC_Invoke_specs_1	/* Additional specs */
};

