/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#include "MessageType.h"

static asn_per_constraints_t asn_PER_type_MessageType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_MessageType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MessageType, choice.unidirectional),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unidirectional,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unidirectional"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageType, choice.begin),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Begin,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"begin"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageType, choice.end),
		(ASN_TAG_CLASS_APPLICATION | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_End,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"end"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageType, choice.Continue),
		(ASN_TAG_CLASS_APPLICATION | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Continue,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"continue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageType, choice.abort),
		(ASN_TAG_CLASS_APPLICATION | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Abort,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"abort"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MessageType_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 0, 0, 0 }, /* unidirectional */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 1, 0, 0 }, /* begin */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 2, 0, 0 }, /* end */
    { (ASN_TAG_CLASS_APPLICATION | (5 << 2)), 3, 0, 0 }, /* continue */
    { (ASN_TAG_CLASS_APPLICATION | (7 << 2)), 4, 0, 0 } /* abort */
};
static asn_CHOICE_specifics_t asn_SPC_MessageType_specs_1 = {
	sizeof(struct MessageType),
	offsetof(struct MessageType, _asn_ctx),
	offsetof(struct MessageType, present),
	sizeof(((struct MessageType *)0)->present),
	asn_MAP_MessageType_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MessageType = {
	"MessageType",
	"MessageType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_MessageType_constr_1, CHOICE_constraint },
	asn_MBR_MessageType_1,
	5,	/* Elements count */
	&asn_SPC_MessageType_specs_1	/* Additional specs */
};

