/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_OPERATION_H_
#define	_OPERATION_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OPERATION_PR {
	OPERATION_PR_NOTHING,	/* No components present */
	OPERATION_PR_localValue,
	OPERATION_PR_globalValue
} OPERATION_PR;

/* OPERATION */
typedef struct OPERATION {
	OPERATION_PR present;
	union OPERATION_u {
		long	 localValue;
		OBJECT_IDENTIFIER_t	 globalValue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OPERATION_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OPERATION;
extern asn_CHOICE_specifics_t asn_SPC_OPERATION_specs_1;
extern asn_TYPE_member_t asn_MBR_OPERATION_1[2];
extern asn_per_constraints_t asn_PER_type_OPERATION_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _OPERATION_H_ */
#include <asn_internal.h>
