/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_MessageType;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module TCAPMessages in TCAPMessages.asn */
	&asn_DEF_MessageType,	
	0
};

