/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#include "ReturnResult.h"

static asn_TYPE_member_t asn_MBR_result_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct result, operationCode),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_OPERATION,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"operationCode"
		},
	{ ATF_ANY_TYPE | ATF_NOFLAGS, 0, offsetof(struct result, parameter),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"parameter"
		},
};
static const ber_tlv_tag_t asn_DEF_result_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_result_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* localValue */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* globalValue */
};
static asn_SEQUENCE_specifics_t asn_SPC_result_specs_3 = {
	sizeof(struct result),
	offsetof(struct result, _asn_ctx),
	asn_MAP_result_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_result_3 = {
	"result",
	"result",
	&asn_OP_SEQUENCE,
	asn_DEF_result_tags_3,
	sizeof(asn_DEF_result_tags_3)
		/sizeof(asn_DEF_result_tags_3[0]), /* 1 */
	asn_DEF_result_tags_3,	/* Same as above */
	sizeof(asn_DEF_result_tags_3)
		/sizeof(asn_DEF_result_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_result_3,
	2,	/* Elements count */
	&asn_SPC_result_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ReturnResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReturnResult, invokeID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_InvokeIdType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"invokeID"
		},
	{ ATF_POINTER, 1, offsetof(struct ReturnResult, result),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_result_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"result"
		},
};
static const int asn_MAP_ReturnResult_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ReturnResult_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReturnResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* invokeID */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* result */
};
asn_SEQUENCE_specifics_t asn_SPC_ReturnResult_specs_1 = {
	sizeof(struct ReturnResult),
	offsetof(struct ReturnResult, _asn_ctx),
	asn_MAP_ReturnResult_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ReturnResult_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReturnResult = {
	"ReturnResult",
	"ReturnResult",
	&asn_OP_SEQUENCE,
	asn_DEF_ReturnResult_tags_1,
	sizeof(asn_DEF_ReturnResult_tags_1)
		/sizeof(asn_DEF_ReturnResult_tags_1[0]), /* 1 */
	asn_DEF_ReturnResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReturnResult_tags_1)
		/sizeof(asn_DEF_ReturnResult_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ReturnResult_1,
	2,	/* Elements count */
	&asn_SPC_ReturnResult_specs_1	/* Additional specs */
};

