/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#include "ReturnError.h"

asn_TYPE_member_t asn_MBR_ReturnError_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReturnError, invokeID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_InvokeIdType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"invokeID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReturnError, errorCode),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ERROR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"errorCode"
		},
	{ ATF_ANY_TYPE | ATF_POINTER, 1, offsetof(struct ReturnError, parameter),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"parameter"
		},
};
static const int asn_MAP_ReturnError_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ReturnError_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReturnError_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* invokeID */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* localValue */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 } /* globalValue */
};
asn_SEQUENCE_specifics_t asn_SPC_ReturnError_specs_1 = {
	sizeof(struct ReturnError),
	offsetof(struct ReturnError, _asn_ctx),
	asn_MAP_ReturnError_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ReturnError_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReturnError = {
	"ReturnError",
	"ReturnError",
	&asn_OP_SEQUENCE,
	asn_DEF_ReturnError_tags_1,
	sizeof(asn_DEF_ReturnError_tags_1)
		/sizeof(asn_DEF_ReturnError_tags_1[0]), /* 1 */
	asn_DEF_ReturnError_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReturnError_tags_1)
		/sizeof(asn_DEF_ReturnError_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ReturnError_1,
	3,	/* Elements count */
	&asn_SPC_ReturnError_specs_1	/* Additional specs */
};

