/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_ReturnResult_H_
#define	_ReturnResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InvokeIdType.h"
#include "OPERATION.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReturnResult */
typedef struct ReturnResult {
	InvokeIdType_t	 invokeID;
	struct result {
		OPERATION_t	 operationCode;
		ANY_t	 parameter;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *result;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReturnResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReturnResult;
extern asn_SEQUENCE_specifics_t asn_SPC_ReturnResult_specs_1;
extern asn_TYPE_member_t asn_MBR_ReturnResult_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ReturnResult_H_ */
#include <asn_internal.h>
