/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_ReturnError_H_
#define	_ReturnError_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InvokeIdType.h"
#include "ERROR.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReturnError */
typedef struct ReturnError {
	InvokeIdType_t	 invokeID;
	ERROR_t	 errorCode;
	ANY_t	*parameter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReturnError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReturnError;
extern asn_SEQUENCE_specifics_t asn_SPC_ReturnError_specs_1;
extern asn_TYPE_member_t asn_MBR_ReturnError_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ReturnError_H_ */
#include <asn_internal.h>
