/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_Unidirectional_H_
#define	_Unidirectional_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DialoguePortion.h"
#include "ComponentPortion.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Unidirectional */
typedef struct Unidirectional {
	DialoguePortion_t	*dialoguePortion	/* OPTIONAL */;
	ComponentPortion_t	 components;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Unidirectional_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Unidirectional;
extern asn_SEQUENCE_specifics_t asn_SPC_Unidirectional_specs_1;
extern asn_TYPE_member_t asn_MBR_Unidirectional_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Unidirectional_H_ */
#include <asn_internal.h>
