/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "TCAPMessages.asn"
 * 	`asn1c -no-gen-OER`
 */

#include "Unidirectional.h"

asn_TYPE_member_t asn_MBR_Unidirectional_1[] = {
	{ ATF_POINTER, 1, offsetof(struct Unidirectional, dialoguePortion),
		(ASN_TAG_CLASS_APPLICATION | (11 << 2)),
		0,
		&asn_DEF_DialoguePortion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dialoguePortion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Unidirectional, components),
		(ASN_TAG_CLASS_APPLICATION | (12 << 2)),
		0,
		&asn_DEF_ComponentPortion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"components"
		},
};
static const int asn_MAP_Unidirectional_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_Unidirectional_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Unidirectional_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 0, 0, 0 }, /* dialoguePortion */
    { (ASN_TAG_CLASS_APPLICATION | (12 << 2)), 1, 0, 0 } /* components */
};
asn_SEQUENCE_specifics_t asn_SPC_Unidirectional_specs_1 = {
	sizeof(struct Unidirectional),
	offsetof(struct Unidirectional, _asn_ctx),
	asn_MAP_Unidirectional_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_Unidirectional_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Unidirectional = {
	"Unidirectional",
	"Unidirectional",
	&asn_OP_SEQUENCE,
	asn_DEF_Unidirectional_tags_1,
	sizeof(asn_DEF_Unidirectional_tags_1)
		/sizeof(asn_DEF_Unidirectional_tags_1[0]), /* 1 */
	asn_DEF_Unidirectional_tags_1,	/* Same as above */
	sizeof(asn_DEF_Unidirectional_tags_1)
		/sizeof(asn_DEF_Unidirectional_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Unidirectional_1,
	2,	/* Elements count */
	&asn_SPC_Unidirectional_specs_1	/* Additional specs */
};

